[build]
  publish = "Static"

[[redirects]]
  from = "/api/*"
  to = "https://YOUR-BACKEND-DOMAIN/api/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


