[build]
  publish = "Static"

[[redirects]]
  from = "/api/*"
  to = "https://link-2-text.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Authorization = "*"}

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


